import type { INodeProperties } from 'n8n-workflow';

/** displayOptions helper: show a property for a resource + set of operations. */
const showFor = (resource: string, operations: string[]): INodeProperties['displayOptions'] => ({
	show: { resource: [resource], operation: operations },
});

/** displayOptions helper for a field shared across resources (operation names are unique). */
const showForAny = (
	resources: string[],
	operations: string[],
): INodeProperties['displayOptions'] => ({
	show: { resource: resources, operation: operations },
});

const resourceSelect: INodeProperties = {
	displayName: 'Resource',
	name: 'resource',
	type: 'options',
	noDataExpression: true,
	options: [
		{ name: 'Advert', value: 'advert' },
		{ name: 'Channel', value: 'channel' },
		{ name: 'Contact', value: 'contact' },
		{ name: 'Device', value: 'device' },
		{ name: 'Diagnostic', value: 'diagnostics' },
		{ name: 'Flood Scope', value: 'floodScope' },
		{ name: 'Message', value: 'message' },
		{ name: 'Repeater', value: 'repeater' },
	],
	default: 'device',
};

const operationSelectors: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['device'] } },
		default: 'getSelfInfo',
		options: [
			{ name: 'Factory Reset', value: 'factoryReset', action: 'Factory reset the device', description: 'Erase the filesystem and reboot (destructive)' },
			{ name: 'Get Allowed Repeat Frequencies', value: 'getAllowedRepeatFreq', action: 'Get allowed repeat frequencies', description: 'Read the permitted repeater frequency ranges' },
			{ name: 'Get Auto Add Config', value: 'getAutoAddConfig', action: 'Get auto add config', description: 'Read the automatic contact-add configuration' },
			{ name: 'Get Battery Voltage', value: 'getBatteryVoltage', action: 'Get battery voltage', description: 'Read battery and storage status' },
			{ name: 'Get Custom Variables', value: 'getCustomVars', action: 'Get custom variables', description: 'Read device custom variables/settings' },
			{ name: 'Get Device Time', value: 'getDeviceTime', action: 'Get device time', description: 'Read the device RTC clock' },
			{ name: 'Get Self Info', value: 'getSelfInfo', action: 'Get device self info', description: 'Read identity and radio configuration (AppStart)' },
			{ name: 'Get Stats', value: 'getStats', action: 'Get device stats', description: 'Read core/radio/packet statistics' },
			{ name: 'Get Tuning Parameters', value: 'getTuningParams', action: 'Get tuning parameters', description: 'Read rx-delay and airtime-factor tuning' },
			{ name: 'Reboot', value: 'reboot', action: 'Reboot the device', description: 'Reboot the MeshCore device' },
			{ name: 'Set Advert Location', value: 'setAdvertLatLong', action: 'Set advert location', description: 'Set the advertised latitude/longitude' },
			{ name: 'Set Advert Name', value: 'setAdvertName', action: 'Set advert name', description: 'Set the node name advertised to the mesh' },
			{ name: 'Set Auto Add Config', value: 'setAutoAddConfig', action: 'Set auto add config', description: 'Configure automatic contact adding' },
			{ name: 'Set Custom Variable', value: 'setCustomVar', action: 'Set a custom variable', description: 'Set a device custom variable/setting' },
			{ name: 'Set Device Pin', value: 'setDevicePin', action: 'Set device pin', description: 'Set or clear the connection PIN (0 to clear)' },
			{ name: 'Set Device Time', value: 'setDeviceTime', action: 'Set device time', description: 'Set the device RTC clock' },
			{ name: 'Set Path Hash Mode', value: 'setPathHashMode', action: 'Set path hash mode', description: 'Set the path hashing mode (0-2)' },
			{ name: 'Set TX Power', value: 'setTxPower', action: 'Set transmit power', description: 'Set the LoRa transmit power (dBm)' },
			{ name: 'Sync Device Time', value: 'syncDeviceTime', action: 'Sync device time', description: 'Set the device clock to the current host time' },
		],
	},
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['contact'] } },
		default: 'getAll',
		options: [
			{ name: 'Add or Update', value: 'addOrUpdate', action: 'Add or update a contact', description: 'Add a new contact or update an existing one' },
			{ name: 'Export', value: 'export', action: 'Export a contact', description: 'Export a contact (or all) as a shareable advert' },
			{ name: 'Find by Name', value: 'findByName', action: 'Find a contact by name', description: 'Find the first contact with an exact name match' },
			{ name: 'Find by Public Key Prefix', value: 'findByPublicKeyPrefix', action: 'Find a contact by public key prefix', description: 'Find the first contact whose public key starts with the given prefix' },
			{ name: 'Get Advert Path', value: 'getAdvertPath', action: 'Get a contact advert path', description: 'Read the stored advert path for a contact' },
			{ name: 'Get by Key', value: 'getByKey', action: 'Get a contact by public key', description: 'Look up a contact by its full public key' },
			{ name: 'Get Many', value: 'getAll', action: 'Get many contacts', description: 'List many known contacts' },
			{ name: 'Import', value: 'import', action: 'Import a contact', description: 'Import a contact from an advert packet' },
			{ name: 'Remove', value: 'remove', action: 'Remove a contact', description: 'Delete a contact from the device' },
			{ name: 'Reset Path', value: 'resetPath', action: 'Reset a contact path', description: 'Reset the stored route to a contact (revert to flood)' },
			{ name: 'Set Path', value: 'setPath', action: 'Set a contact path', description: 'Set an explicit route (out path) to a contact' },
			{ name: 'Share', value: 'share', action: 'Share a contact', description: 'Broadcast a contact to the mesh' },
		],
	},
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['message'] } },
		default: 'sendDirect',
		options: [
			{ name: 'Await Delivery', value: 'awaitDelivery', action: 'Await a delivery confirmation', description: 'Wait for the delivery confirmation (ack) of an already-sent message' },
			{ name: 'Get Waiting Messages', value: 'getWaiting', action: 'Get waiting messages', description: 'Drain all messages queued on the device' },
			{ name: 'Send Channel Message', value: 'sendChannel', action: 'Send a channel message', description: 'Send a text message to a channel' },
			{ name: 'Send Direct Message', value: 'sendDirect', action: 'Send a direct message', description: 'Send a text message to a contact by public key; enable Reliable Delivery for retries + delivery confirmation' },
			{ name: 'Send Direct Message and Await Reply', value: 'sendDirectAwaitReply', action: 'Send a direct message and await reply', description: 'Send a direct message and wait for the contact to reply' },
			{ name: 'Sync Next Message', value: 'syncNext', action: 'Sync the next message', description: 'Fetch the next single queued message' },
		],
	},
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['channel'] } },
		default: 'getAll',
		options: [
			{ name: 'Delete Channel', value: 'delete', action: 'Delete a channel', description: 'Clear a channel at an index' },
			{ name: 'Find by Name', value: 'findByName', action: 'Find a channel by name', description: 'Find the first channel with an exact name match' },
			{ name: 'Find by Secret', value: 'findBySecret', action: 'Find a channel by secret', description: 'Find the first channel matching a secret' },
			{ name: 'Get Channel', value: 'get', action: 'Get a channel', description: 'Read a single channel by index' },
			{ name: 'Get Many', value: 'getAll', action: 'Get many channels', description: 'List many configured channels' },
			{ name: 'Send Data', value: 'sendData', action: 'Send channel data', description: 'Send a binary datagram to a channel' },
			{ name: 'Set Channel', value: 'set', action: 'Set a channel', description: 'Create or update a channel at an index' },
		],
	},
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['advert'] } },
		default: 'flood',
		options: [
			{ name: 'Send Flood Advert', value: 'flood', action: 'Send a flood advert', description: 'Broadcast a flood advertisement' },
			{ name: 'Send Zero-Hop Advert', value: 'zeroHop', action: 'Send a zero hop advert', description: 'Broadcast a zero-hop advertisement' },
		],
	},
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['diagnostics'] } },
		default: 'getStatus',
		options: [
			{ name: 'Await Event', value: 'awaitEvent', action: 'Await a push event', description: 'Wait for the next push event of a chosen type' },
			{ name: 'Discover Path', value: 'discoverPath', action: 'Discover a path', description: 'Flood a path-discovery request and wait for the discovered route' },
			{ name: 'Get Neighbours', value: 'getNeighbours', action: 'Get repeater neighbours', description: 'List neighbours seen by a repeater (firmware v1.9.0+)' },
			{ name: 'Get Status', value: 'getStatus', action: 'Get status from a node', description: 'Request a status response from a contact/repeater' },
			{ name: 'Get Telemetry', value: 'getTelemetry', action: 'Get telemetry from a node', description: 'Request telemetry from a contact/repeater' },
			{ name: 'Send Binary Request', value: 'sendBinaryRequest', action: 'Send a binary request', description: 'Send a raw binary request and return the response' },
			{ name: 'Send Path Discovery', value: 'sendPathDiscovery', action: 'Send a path discovery request', description: 'Flood a path-discovery request to a contact (result arrives async)' },
			{ name: 'Trace Path', value: 'tracePath', action: 'Trace a path', description: 'Trace the route to/along a path' },
		],
	},
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['repeater'] } },
		default: 'login',
		options: [
			{ name: 'Has Connection', value: 'hasConnection', action: 'Check repeater connection', description: 'Check whether there is an active connection to a node' },
			{ name: 'Login', value: 'login', action: 'Log in to a repeater', description: 'Authenticate to a repeater/room server' },
			{ name: 'Logout', value: 'logout', action: 'Log out of a repeater', description: 'End the connection/session to a node' },
			{ name: 'Send Anonymous Request', value: 'sendAnonReq', action: 'Send an anonymous request', description: 'Send an anonymous request to a contact' },
			{ name: 'Send CLI Command', value: 'sendCliCommand', action: 'Send a CLI command', description: 'Send a CLI command to a repeater/room and wait for the response (log in first)' },
			{ name: 'Send Control Data', value: 'sendControlData', action: 'Send control data', description: 'Send a zero-hop control datagram' },
			{ name: 'Sign Data', value: 'sign', action: 'Sign data', description: 'Sign arbitrary data with the device key' },
		],
	},
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['floodScope'] } },
		default: 'set',
		options: [
			{ name: 'Clear Scope', value: 'clear', action: 'Clear the flood scope', description: 'Clear the configured flood scope key' },
			{ name: 'Get Default', value: 'getDefault', action: 'Get the default flood scope', description: 'Read the saved default flood scope name and key' },
			{ name: 'Set Default', value: 'setDefault', action: 'Set the default flood scope', description: 'Save a default flood scope name and key' },
			{ name: 'Set Scope', value: 'set', action: 'Set the flood scope', description: 'Set a 16-byte transport key as the flood scope' },
		],
	},
];

const fields: INodeProperties[] = [
	// public key (hex) shared by message/diagnostics/repeater
	{
		displayName: 'Contact Public Key',
		name: 'contactPublicKey',
		type: 'string',
		default: '',
		required: true,
		placeholder: 'e.g. a1b2c3d4e5f6...',
		description: 'Target public key as hex (first 6 bytes are used for routing)',
		displayOptions: showForAny(
			['message', 'diagnostics', 'repeater'],
			[
				'sendDirect',
				'sendDirectAwaitReply',
				'getStatus',
				'getTelemetry',
				'login',
				'getNeighbours',
				'sendBinaryRequest',
				'sendPathDiscovery',
				'discoverPath',
				'hasConnection',
				'logout',
				'sendAnonReq',
				'sendCliCommand',
			],
		),
	},
	// contact public key (required) for remove/share/resetPath
	{
		displayName: 'Public Key',
		name: 'publicKey',
		type: 'string',
		default: '',
		required: true,
		description: 'Contact public key as hex',
		displayOptions: showFor('contact', ['remove', 'share', 'resetPath', 'addOrUpdate', 'setPath', 'getByKey', 'getAdvertPath']),
	},
	// optional public key for export
	{
		displayName: 'Public Key',
		name: 'exportPublicKey',
		type: 'string',
		default: '',
		description: 'Contact public key as hex; leave empty to export all contacts',
		displayOptions: showFor('contact', ['export']),
	},
	{
		displayName: 'Public Key Prefix',
		name: 'publicKeyPrefix',
		type: 'string',
		default: '',
		required: true,
		description: 'Public key prefix as hex (1+ bytes)',
		displayOptions: showFor('contact', ['findByPublicKeyPrefix']),
	},
	{
		displayName: 'Advert Packet',
		name: 'advertPacket',
		type: 'string',
		default: '',
		required: true,
		description: 'Raw advert packet bytes as hex',
		displayOptions: showFor('contact', ['import']),
	},
	// name (advert name / contact name / channel name)
	{
		displayName: 'Name',
		name: 'name',
		type: 'string',
		default: '',
		required: true,
		description: 'Name value',
		displayOptions: showForAny(['device', 'contact', 'channel'], ['setAdvertName', 'findByName', 'set', 'addOrUpdate']),
	},
	// message body
	{
		displayName: 'Message',
		name: 'message',
		type: 'string',
		typeOptions: { rows: 2 },
		default: '',
		required: true,
		description: 'Text to send',
		displayOptions: showFor('message', ['sendDirect', 'sendChannel', 'sendDirectAwaitReply']),
	},
	{
		displayName: 'Text Type',
		name: 'txtType',
		type: 'options',
		default: 0,
		options: [
			{ name: 'Plain', value: 0 },
			{ name: 'CLI Data', value: 1 },
			{ name: 'Signed Plain', value: 2 },
		],
		description: 'Message text type',
		displayOptions: showFor('message', ['sendDirect', 'sendDirectAwaitReply']),
	},
	// channel index
	{
		displayName: 'Channel Index',
		name: 'channelIdx',
		type: 'number',
		default: 0,
		required: true,
		description: 'Zero-based channel index',
		displayOptions: showForAny(['message', 'channel'], ['sendChannel', 'get', 'set', 'delete', 'sendData']),
	},
	// channel secret (hex)
	{
		displayName: 'Secret',
		name: 'secret',
		type: 'string',
		typeOptions: { password: true },
		default: '',
		required: true,
		description: 'Channel secret as hex (16 bytes)',
		displayOptions: showFor('channel', ['set', 'findBySecret']),
	},
	// device time
	{
		displayName: 'Epoch Seconds',
		name: 'epochSeconds',
		type: 'number',
		default: 0,
		description: 'Unix time in seconds; leave 0 to use the current host time',
		displayOptions: showFor('device', ['setDeviceTime']),
	},
	{
		displayName: 'Latitude',
		name: 'latitude',
		type: 'number',
		default: 0,
		required: true,
		displayOptions: showForAny(['device', 'contact'], ['setAdvertLatLong', 'addOrUpdate']),
	},
	{
		displayName: 'Longitude',
		name: 'longitude',
		type: 'number',
		default: 0,
		required: true,
		displayOptions: showForAny(['device', 'contact'], ['setAdvertLatLong', 'addOrUpdate']),
	},
	{
		displayName: 'TX Power (dBm)',
		name: 'txPower',
		type: 'number',
		default: 20,
		required: true,
		displayOptions: showFor('device', ['setTxPower']),
	},
	{
		displayName: 'Stats Type',
		name: 'statsType',
		type: 'options',
		default: 0,
		options: [
			{ name: 'Core', value: 0 },
			{ name: 'Radio', value: 1 },
			{ name: 'Packets', value: 2 },
		],
		displayOptions: showFor('device', ['getStats']),
	},
	// repeater password
	{
		displayName: 'Password',
		name: 'password',
		type: 'string',
		typeOptions: { password: true },
		default: '',
		required: true,
		description: 'Repeater/room login password',
		displayOptions: showFor('repeater', ['login']),
	},

	// --- complex operation fields --------------------------------------------
	{
		displayName: 'Contact Type',
		name: 'type',
		type: 'number',
		default: 1,
		required: true,
		description: 'Advert type: 1=Chat, 2=Repeater, 3=Room',
		displayOptions: showFor('contact', ['addOrUpdate']),
	},
	{
		displayName: 'Flags',
		name: 'flags',
		type: 'number',
		default: 0,
		description: 'Contact flags bitfield',
		displayOptions: showFor('contact', ['addOrUpdate']),
	},
	{
		displayName: 'Last Advert',
		name: 'lastAdvert',
		type: 'number',
		default: 0,
		description: 'Unix time (seconds) of the last advert from this contact',
		displayOptions: showFor('contact', ['addOrUpdate']),
	},
	{
		displayName: 'Out Path',
		name: 'outPath',
		type: 'string',
		default: '',
		description: 'Explicit route bytes as hex; leave empty for flood routing',
		displayOptions: showFor('contact', ['addOrUpdate']),
	},
	{
		displayName: 'Path',
		name: 'path',
		type: 'string',
		default: '',
		description: 'Route bytes as hex (each byte is a hop); leave empty for a zero-hop path',
		displayOptions: showForAny(['contact', 'diagnostics'], ['setPath', 'tracePath']),
	},
	{
		displayName: 'Routing',
		name: 'routing',
		type: 'options',
		default: 'flood',
		description: 'How to route the datagram into the channel',
		options: [
			{ name: 'Flood', value: 'flood', description: 'Broadcast across the mesh (applies the device flood scope, if set)' },
			{ name: 'Direct', value: 'direct', description: 'Send along a specific repeater path' },
		],
		displayOptions: showFor('channel', ['sendData']),
	},
	{
		displayName: 'Path',
		name: 'path',
		type: 'string',
		default: '',
		required: true,
		description: 'Route bytes as hex (each byte is a one-hop hash); empty sends zero-hop direct',
		displayOptions: {
			show: { resource: ['channel'], operation: ['sendData'], routing: ['direct'] },
		},
	},
	{
		displayName: 'Data Type',
		name: 'dataType',
		type: 'number',
		default: 65535,
		required: true,
		description:
			'Application data type tag (uint16) passed through to receivers. 0 is reserved/rejected; 65535 (0xFFFF) is the developer namespace.',
		displayOptions: showFor('channel', ['sendData']),
	},
	{
		displayName: 'Payload',
		name: 'payload',
		type: 'string',
		default: '',
		required: true,
		description: 'Datagram payload as hex',
		displayOptions: showFor('channel', ['sendData']),
	},
	{
		displayName: 'Request Data',
		name: 'requestData',
		type: 'string',
		default: '',
		required: true,
		description: 'Binary request bytes as hex (first byte is the request type)',
		displayOptions: showForAny(['diagnostics', 'repeater'], ['sendBinaryRequest', 'sendAnonReq']),
	},
	{
		displayName: 'Extra Timeout (Ms)',
		name: 'extraTimeoutMs',
		type: 'number',
		default: 1000,
		description: 'Extra time to wait beyond the estimated round-trip',
		displayOptions: showFor('diagnostics', ['tracePath', 'sendBinaryRequest']),
	},
	{
		displayName: 'Count',
		name: 'count',
		type: 'number',
		default: 10,
		description: 'How many neighbours to fetch',
		displayOptions: showFor('diagnostics', ['getNeighbours']),
	},
	{
		displayName: 'Offset',
		name: 'offset',
		type: 'number',
		default: 0,
		description: 'Result offset for pagination',
		displayOptions: showFor('diagnostics', ['getNeighbours']),
	},
	{
		displayName: 'Order By',
		name: 'orderBy',
		type: 'options',
		default: 0,
		options: [
			{ name: 'Newest to Oldest', value: 0 },
			{ name: 'Oldest to Newest', value: 1 },
			{ name: 'Strongest to Weakest', value: 2 },
			{ name: 'Weakest to Strongest', value: 3 },
		],
		displayOptions: showFor('diagnostics', ['getNeighbours']),
	},
	{
		displayName: 'Public Key Prefix Length',
		name: 'publicKeyPrefixLength',
		type: 'number',
		default: 8,
		description: 'Number of public key prefix bytes to return per neighbour',
		displayOptions: showFor('diagnostics', ['getNeighbours']),
	},
	{
		displayName: 'Data',
		name: 'data',
		type: 'string',
		default: '',
		required: true,
		description: 'Data to sign, as hex',
		displayOptions: showFor('repeater', ['sign']),
	},
	{
		displayName: 'Transport Key',
		name: 'transportKey',
		type: 'string',
		typeOptions: { password: true },
		default: '',
		required: true,
		description: '16-byte transport key as hex',
		displayOptions: showFor('floodScope', ['set', 'setDefault']),
	},

	// --- §8 gap-command fields -----------------------------------------------
	{
		displayName: 'Pin',
		name: 'pin',
		type: 'number',
		default: 0,
		required: true,
		description: 'Connection PIN (a 6-digit number, or 0 to clear)',
		displayOptions: showFor('device', ['setDevicePin']),
	},
	{
		displayName: 'Variable Name',
		name: 'varName',
		type: 'string',
		default: '',
		required: true,
		description: 'Custom variable/setting name',
		displayOptions: showFor('device', ['setCustomVar']),
	},
	{
		displayName: 'Variable Value',
		name: 'varValue',
		type: 'string',
		default: '',
		required: true,
		description: 'Custom variable/setting value',
		displayOptions: showFor('device', ['setCustomVar']),
	},
	{
		displayName: 'Path Hash Mode',
		name: 'pathHashMode',
		type: 'options',
		default: 0,
		options: [
			{ name: 'Mode 0', value: 0 },
			{ name: 'Mode 1', value: 1 },
			{ name: 'Mode 2', value: 2 },
		],
		displayOptions: showFor('device', ['setPathHashMode']),
	},
	{
		displayName: 'Auto Add Config',
		name: 'autoAddConfig',
		type: 'number',
		default: 0,
		required: true,
		description: 'Auto-add configuration bitfield',
		displayOptions: showFor('device', ['setAutoAddConfig']),
	},
	{
		displayName: 'Auto Add Max Hops',
		name: 'autoAddMaxHops',
		type: 'number',
		default: 0,
		description: 'Maximum hops for auto-added contacts',
		displayOptions: showFor('device', ['setAutoAddConfig']),
	},
	{
		displayName: 'Confirm',
		name: 'confirm',
		type: 'boolean',
		default: false,
		description: 'Whether to confirm this destructive factory reset',
		displayOptions: showFor('device', ['factoryReset']),
	},
	{
		displayName: 'Control Data',
		name: 'controlData',
		type: 'string',
		default: '',
		required: true,
		description: 'Control datagram bytes as hex (first byte must have bit 0x80 set)',
		displayOptions: showFor('repeater', ['sendControlData']),
	},
	{
		displayName: 'Scope Name',
		name: 'scopeName',
		type: 'string',
		default: '',
		required: true,
		description: 'Default flood scope name (max 30 chars)',
		displayOptions: showFor('floodScope', ['setDefault']),
	},

	// --- await / combined operation fields -----------------------------------
	{
		displayName: 'CLI Command',
		name: 'command',
		type: 'string',
		default: '',
		required: true,
		placeholder: 'e.g. reboot',
		description: 'CLI command text to send to the repeater/room',
		displayOptions: showFor('repeater', ['sendCliCommand']),
	},
	{
		displayName: 'Ack Code',
		name: 'ackCode',
		type: 'number',
		default: 0,
		required: true,
		description: 'The expected ack code (from a prior Send Direct Message output)',
		displayOptions: showFor('message', ['awaitDelivery']),
	},
	{
		displayName: 'Reliable Delivery',
		name: 'reliableDelivery',
		type: 'boolean',
		default: false,
		description:
			'Whether to send with delivery retries and confirmation. On Send Direct Message, enabling this turns the node into a reliable-send (path + flood retry phases, throws on non-delivery → red status). On Send Direct Message and Await Reply, it runs the same retry+ack pipeline before listening for the reply. On Send Channel Message, retries are confirmed by hearing a neighbor retransmit the broadcast on the radio (channels have no per-recipient ack); throws if no retransmission heard.',
		displayOptions: showFor('message', ['sendDirect', 'sendDirectAwaitReply', 'sendChannel']),
	},
	{
		displayName: 'Channel Retries',
		name: 'channelRetries',
		type: 'number',
		default: 3,
		description: 'How many times to broadcast the message before giving up',
		displayOptions: {
			show: {
				resource: ['message'],
				operation: ['sendChannel'],
				reliableDelivery: [true],
			},
		},
	},
	{
		displayName: 'Channel Echo Timeout (Ms)',
		name: 'channelEchoTimeoutMs',
		type: 'number',
		default: 8000,
		description:
			'How long to wait per attempt for a neighbor to retransmit our broadcast (heard via the radio LogRxData stream) before retrying',
		displayOptions: {
			show: {
				resource: ['message'],
				operation: ['sendChannel'],
				reliableDelivery: [true],
			},
		},
	},
	// Retry/timeout fields are shown when the operation supports them — either always
	// (awaitDelivery needs ackTimeout) or gated on the Reliable Delivery toggle for
	// sendDirect / sendDirectAwaitReply. Each field is declared once per show set;
	// the displayOptions are kept simple (no `hide` clause) because n8n was matching
	// `reliableDelivery: [false]` on operations where the param doesn't exist.
	{
		displayName: 'Ack Timeout (Ms)',
		name: 'ackTimeoutMs',
		type: 'number',
		default: 15000,
		description: 'How long to wait for the delivery confirmation per attempt',
		displayOptions: showFor('message', ['awaitDelivery']),
	},
	{
		displayName: 'Ack Timeout (Ms)',
		name: 'ackTimeoutMs',
		type: 'number',
		default: 15000,
		description: 'How long to wait for the delivery confirmation per attempt',
		displayOptions: {
			show: {
				resource: ['message'],
				operation: ['sendDirect', 'sendDirectAwaitReply'],
				reliableDelivery: [true],
			},
		},
	},
	{
		displayName: 'Path Retries',
		name: 'pathRetries',
		type: 'number',
		default: 2,
		description:
			'How many times to send along the stored route before resetting it and falling back to flood routing',
		displayOptions: {
			show: {
				resource: ['message'],
				operation: ['sendDirect', 'sendDirectAwaitReply'],
				reliableDelivery: [true],
			},
		},
	},
	{
		displayName: 'Flood Retries',
		name: 'floodRetries',
		type: 'number',
		default: 2,
		description:
			'How many times to retry by flooding (route reset) after the path phase is exhausted',
		displayOptions: {
			show: {
				resource: ['message'],
				operation: ['sendDirect', 'sendDirectAwaitReply'],
				reliableDelivery: [true],
			},
		},
	},
	{
		displayName: 'Force Flood',
		name: 'forceFlood',
		type: 'boolean',
		default: false,
		description:
			'Whether to skip the path phase and reset the route before sending so the message goes via flood from the first attempt',
		displayOptions: {
			show: {
				resource: ['message'],
				operation: ['sendDirect', 'sendDirectAwaitReply'],
				reliableDelivery: [true],
			},
		},
	},
	{
		displayName: 'Reset Path on Flood Fallback',
		name: 'resetPathOnFloodFallback',
		type: 'boolean',
		default: true,
		description:
			'Whether to clear the stored route to the contact when switching from path retries to flood retries. A stale route is the typical reason path attempts fail. Disable only to preserve the route; flood-phase retries then proceed without clearing it (firmware will keep using the same path).',
		displayOptions: {
			show: {
				resource: ['message'],
				operation: ['sendDirect', 'sendDirectAwaitReply'],
				reliableDelivery: [true],
			},
		},
	},
	{
		displayName: 'Reply Timeout (Ms)',
		name: 'replyTimeoutMs',
		type: 'number',
		default: 30000,
		description: 'How long to wait for a reply',
		displayOptions: showForAny(['message', 'repeater'], ['sendDirectAwaitReply', 'sendCliCommand']),
	},
	{
		displayName: 'Result Timeout (Ms)',
		name: 'resultTimeoutMs',
		type: 'number',
		default: 30000,
		description: 'How long to wait for the result/event',
		displayOptions: showFor('diagnostics', ['discoverPath', 'awaitEvent']),
	},
	{
		displayName: 'Event',
		name: 'pushCode',
		type: 'options',
		default: 0x82,
		options: [
			{ name: 'Advert', value: 0x80 },
			{ name: 'Path Updated', value: 0x81 },
			{ name: 'Send Confirmed', value: 0x82 },
			{ name: 'Login Success', value: 0x85 },
			{ name: 'Login Failed', value: 0x86 },
			{ name: 'Status Response', value: 0x87 },
			{ name: 'Trace Data', value: 0x89 },
			{ name: 'New Advert', value: 0x8a },
			{ name: 'Telemetry Response', value: 0x8b },
			{ name: 'Binary Response', value: 0x8c },
			{ name: 'Path Discovery Response', value: 0x8d },
			{ name: 'Control Data', value: 0x8e },
		],
		description: 'Which push event to wait for',
		displayOptions: showFor('diagnostics', ['awaitEvent']),
	},
];

export const properties: INodeProperties[] = [resourceSelect, ...operationSelectors, ...fields];
